### ISSUE TITLE
Argo Blockchain BTC count

### ISSUE THREAD

**Issue by VictorD10** [BuyBitcoinWorldwide/bitcointreasuries#24]
Not sure how this works, I've never used GitHub before.

I am currently conducting my Master Thesis in Strategic Corporate finance on the topic of short-term impact of institutional crypto acquisitions and position announcement. Your website has been very helpful in gathering data for my research! I noticed that your count for BTC amount of Argo Blockchain is incorrect. It currently stands at 2,317 BTC according to the London Stock Exchange filing of November 2021:
https://www.londonstockexchange.com/news-article/ARB/november-2021-operational-update/15239246

Best,

Victor

PS: If you are interested in the outcome of my research, or have extra data that is not present on your website and think could be beneficial to me, feel free to shoot me an email at: v.desmedt@student.maastrichtuniversity.nl

**Comment by VictorD10** [comment]
Fortress Technology: 168.2 BTC as of 31/12/2020
https://www.sedar.com/GetFile.do?lang=EN&docClass=5&issuerNo=00032400&issuerType=03&projectNo=03213388&docId=4947407

**Comment by JTuwiner** [comment]
Thanks, we'll update these

**Comment by VictorD10** [comment]
Neptune Digital Assets - 110 BTC
https://neptunedigitalassets.com/neptune-digital-assets-announces-q3-financial-summary-and-corporate-update/

**Comment by JTuwiner** [comment]
updated! thank you

**Comment by VictorD10** [comment]
Merry Christmas!
El Salvador did a couple of december purchases, they now own 1391 BTC
150 BTC on December 4th:
https://twitter.com/nayibbukele/status/1467000621354135555?lang=en
https://www.reuters.com/markets/us/bukele-steps-up-el-salvadors-bet-sliding-bitcoin-buys-another-150-coins-2021-12-05/

21 BTC on December 21st:
https://cointelegraph.com/news/el-salvador-buys-21-bitcoin-to-celebrate-december-21-2021

**Comment by VictorD10** [comment]
Graysacle (GBTC) Q3 10-Q SEC filing: 648,068.8 BTC
https://sec.report/Document/0001564590-21-054757/

**Comment by JTuwiner** [comment]
updated, thanks!
