### ISSUE TITLE
CORZ IPO

### ISSUE THREAD

**Issue by LukeParker** [BuyBitcoinWorldwide/bitcointreasuries#28]
Core Scientific just IPO'd on Nasdaq, and claims to hold "In Excess of 5,000 Bitcoins on Balance Sheet."
https://twitter.com/TexanHodl/status/1484267181995134982

Their IPO press release says: "At the end of 2021, Core Scientific held nearly 5,300 bitcoins on its balance sheet."
https://investors.corescientific.com/investors/news/news-details/2022/Core-Scientific-to-Begin-Trading-on-Nasdaq/default.aspx

...But I can't find the exact number of coins as of today. It will likely require contacting them.... The twitter account above is an employee there. A better contact is their Chief Economist, Allison Reichel @ https://twitter.com/AllisonReichel 

Both of them are constantly on bitcoin twitter so I'm surprised they haven't submitted this themselves.

**Comment by JTuwiner** [comment]
Thanks for posting this! We will look into adding if we can find a good source.
