### ISSUE TITLE
HUT8 BTC balance updat

### ISSUE THREAD

**Issue by salsubai** [BuyBitcoinWorldwide/bitcointreasuries#3]
Hi,
HUT8 balance is not updated, latest update is 3,522 as of 12 May update upon Q1 results announcement.
Quote:
“Our current Bitcoin balance, including 1,000 Bitcoin loaned as part of the Company’s fiat yield strategy, is approximately 3,522 Bitcoin.”

Source: 
https://hut8mining.com/hut-8-achieves-record-level-revenue-results-in-q1-2021-balance-sheet-grows-134-over-fiscal-2020
& Q1 2021 results and MD&A documents.

**Comment by JTuwiner** [comment]
updated. thanks!
