### ISSUE TITLE
Xapo Bank BTC holdings

### ISSUE THREAD

**Issue by darymcgovern** [BuyBitcoinWorldwide/bitcointreasuries#42]
Hello. I'm creating this issue to request the inclusion of Xapo Bank on the Bitcoin treasuries tables.

As of the 31st of August 2023, Xapo Bank had 38,931.0922 BTC under management either directly or through investments. We are audited by KPMG, with PWC providing internal audit services.  Please contact me for supporting information.

Dary McGovern
Chief Operating Officer
Xapo Bank
dary.mcgovern@xapo.com

**Comment by JTuwiner** [comment]
Hi Dary, will add. These are Xapo's BTC or BTC owned on behalf of clients?

**Comment by darymcgovern** [comment]
Hi Jordan. As of the 31st of August 2023, 12,635 BTC are client holdings.

**Comment by JTuwiner** [comment]
added! thanks for the info
