### ISSUE TITLE
Incorrect Bitwise (BITB) BTC holdings

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#45]
Bitwise recently [published](https://twitter.com/BitwiseInvest/status/1750224060620111912) its BITB ETF BTC address, [1CKVszDdUp4ymGceAZpGzYEFr4RPNHYqaM](https://bitinfocharts.com/bitcoin/address/1CKVszDdUp4ymGceAZpGzYEFr4RPNHYqaM), which currently has a balance of 13,576.10 BTC.

[bitcointreasuries.net](https://bitcointreasuries.net/) also shows 13,576 BTC.

While [buybitcoinworldwide.com](https://buybitcoinworldwide.com/treasuries/) currently shows 14,039.5.

**Comment by JTuwiner** [comment]
<img width="1447" alt="Screenshot 2024-01-30 at 8 20 20 AM" src="https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/2924924/b2a582fb-8554-4b6d-84ab-417b43658454">

We're going according to the site. I just checked and it says our number https://bitbetf.com/

Once they update their website, we will update.

**Comment by superclarkk** [comment]
OK, that's fair. The "Bitcoin in Trust" value on [the website](https://bitbetf.com/) is now different to your site. Currently, 26,715.68.

**Comment by JTuwiner** [comment]
we check once at night, once in morning. as soon as there is a change we add it. can't promise it's going to be real-time
