### ISSUE TITLE
Discrepancy between the total of "Totals By Category" and the overall total at the top

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#47]
The overall total is currently 2,079,279, but 822259+501968+277412+477640+39603 is 2,118,882.

![Screenshot from 2024-01-31 14-34-29](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/7795828a-a623-4b8f-a4dd-e6322aed8f9c)

Also, the total for ETFs is 822,109, but it's currently 822,259.

![Screenshot from 2024-01-31 14-45-25](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/0d54d366-c536-4d0c-807e-ab678ad1b66f)

Thanks for a useful resource - keep up the good work!

**Comment by JTuwiner** [comment]
Hey @superclarkk the reason is because the BTC Mining Companies could also be in private or public.

Perhaps that's confusing and I should remove mining from the top.

**Comment by superclarkk** [comment]
Ah, I see. Makes sense. I should have calculated the difference, and then it would have been clear.

Mining Companies at the top is useful because it's one of the most important metrics in crypto.

I think a simple note under the "Totals By Category" would be sufficient, like:

"* Mining Companies will also appear in the public and private categories"
