### ISSUE TITLE
Feature Request: Add summary of changes in BTC holdings per time period to the top table

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#48]
Currently, it's very difficult to keep track of the changes in BTC holdings over time. It would be great if this could be added to the top table, so it would look something like this:

ENTITIES	# OF BTC	VALUE TODAY	% OF 21M	LAST UPDATED
71	2,085,816	$89,897,038,751	9.932%	 February 1, 2024 (latest)
71	2,086,139	$xx,xxx,xxx,xxx	9.934%    January 31, 2024 (1 day ago)
71	2,076,056	$xx,xxx,xxx,xxx	9.886%    January 30, 2024 (2 days ago)
71	2,066,056	$xx,xxx,xxx,xxx	9.786%    January 30, 2024 (1 week ago)
71	2,026,056	$xx,xxx,xxx,xxx	9.686%    December 31, 2024 (1 month ago)
71	2,006,056	$xx,xxx,xxx,xxx	9.586%    February 1, 2023 (1 year ago)

**Comment by JTuwiner** [comment]
that would be nice. problem is we haven't been tracking his historically, so we'd need to check the history of our DB file to get that data. it can be done, but may take some time.

**Comment by JTuwiner** [comment]
We're working on this.
