### ISSUE TITLE
Feature Request: Add summary to all telegram channel updates

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#49]
The [telegram channel](https://t.me/BTCTreasuries) is very useful for getting the latest updates, but the most important metric on the BTC Treasuries page is the summary, and whether total BTC holdings are going up or down over time. It would be really helpful if the top table summary was sent every day, or even with every message, to facilitate this.

**Comment by JTuwiner** [comment]
ill try to include a screenshot from now on
