### ISSUE TITLE
Update ETFs

### ISSUE THREAD

**Issue by E-BTC** [BuyBitcoinWorldwide/bitcointreasuries#5]
Hello, the following ETFs can be added or updated:
https://21shares.com/product/abtc/ which is actually an ETP (pretty similar though) already in the list, now holds 6141.89 Bitcoins;
https://qrasset.com.br/qbtc11/ which is the first full Bitcoin ETF in Latin America and now holds 727.2680597 Bitcoins;
https://www.hashdex.com.br/en/hdexbh/portfolio-composition which is a Brazilian ETF that now holds 8650.54848 Bitcoins.

**Comment by JTuwiner** [comment]
working on this. thanks!

**Comment by JTuwiner** [comment]
updated: https://www.buybitcoinworldwide.com/treasuries/
