### ISSUE TITLE
Grayscale broken links

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#50]
The Grayscale "Filing" link is no longer working (see images). The SEC filings are now on [EDGAR](https://www.sec.gov/edgar/search/#/ciks=0001588489&entityName=Grayscale%2520Bitcoin%2520Trust%2520(BTC)%2520(GBTC)%2520(CIK%25200001588489)), although I haven't found the report showing the total number of Bitcoin it holds.

However, the total BTC holdings is at https://etfs.grayscale.com/gbtc, under "TOTAL BITCOIN IN TRUST".

![image](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/542a2cb3-7082-4a80-b773-b32f4b00c888)

 
![Screenshot from 2024-02-22 13-33-37](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/945b4ca0-2b71-4716-94ae-863d38229a80)

**Comment by JTuwiner** [comment]
ok we'll switch it. thanks!
