### ISSUE TITLE
Summary table "Last Updated" field not updated when "# of BTC" field is updated

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#51]
I just noticed, on the 1st March at about 16:00 UTC, the "# of BTC" field changed without the "Last Updated" field changing. It still says "February 29, 2024".

![Screenshot from 2024-03-01 16-00-04](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/73256d56-425d-4e64-ab97-5467f9830791)

**Comment by JTuwiner** [comment]
working on fix now. thanks.

**Comment by superclarkk** [comment]
Sorry to bug you. I'm afraid this happened again just now.
![image](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/363502b8-2595-4d81-a246-61a7c02e3693)

**Comment by superclarkk** [comment]
Ignore my comment from earlier today. My mistake. Deleted now.

**Comment by JTuwiner** [comment]
no worries, always open to feedback. this was because we added wrapped BTC and since it was new, forgot to to change the date.

**Comment by superclarkk** [comment]
Thanks - appreciated. Unfortunately, the total was updated this morning at around 5am UTC, but the date remains the same.
![Screenshot from 2024-03-03 11-35-44](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/8e77bbc3-fd1f-4a3d-91b5-563802f568d3)

**Comment by JTuwiner** [comment]
ok will keep an eye on it

**Comment by superclarkk** [comment]
Could this be a timezone issue? I guess I assumed the update date is in UTC. It updated at around 2am UTC on 10th March, while the Last Updated date is the 9th.

**Comment by JTuwiner** [comment]
i changed it last night around 8PM EST on March 9th.

**Comment by superclarkk** [comment]
But is the date in EST or UTC?  If you have a global market, it should be in UTC.

The total BTC just updated, and the date is incorrect again
![Screenshot from 2024-03-11 13-45-33](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/46235232-476d-46cc-b54d-51369108ab49)
.

**Comment by JTuwiner** [comment]
Just remember, we're doing this manually. We try our best, but mistakes happen. 

I updated MicroStrategy just now, but forgot to change the date. It has been EST until now, but will look into changing it to UTC.

**Comment by superclarkk** [comment]
I didn't realise it was manual. Ouch - I assumed you were scraping everything.

The date is wrong after the latest update too, I'm afraid. The UTC time is 13:30, which is 9:30 in EST, so it's not the timezone alone causing it. 

So, do you need to manually update the date every time you update a value?

![image](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/a87dc86d-bf94-4677-93db-a48ed6129753)

**Comment by JTuwiner** [comment]
<img width="351" alt="Screenshot 2024-03-13 at 9 44 06 AM" src="https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/2924924/1fd417f6-4e84-42ce-927a-37cebad1797c">

this was updated last night, but i only pushed the change this morning
