### ISSUE TITLE
Mobile version shows different top table entities total compared with desktop version

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#61]
Which of these is correct?

Desktop version shows 91 entities:

![Screenshot from 2024-05-27 16-02-58](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/14554675-6ff4-4ee8-826a-33127b1cac76)

Mobile version shows 71 entities:

![Screenshot from 2024-05-27 16-03-27](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/7647b98e-30a5-4f9d-bada-48a01f4849ea)

**Comment by JTuwiner** [comment]
91 is correct. fixed

**Comment by superclarkk** [comment]
Looks good. It's a lot of entities that have been added, but it's difficult to see exactly which. The list of companies looks the same as before. Could you list them, or some of them?

**Comment by JTuwiner** [comment]
You're saying you want a feed of new entities?

**Comment by superclarkk** [comment]
Not necessarily, although that's a good idea.

I just want to know, in your reply, what entities have been added in the last update. I can't see any difference, despite 20 being added. In which category were they added to?

**Comment by JTuwiner** [comment]
20 were not added. the number had just not been updated for a long time.

**Comment by superclarkk** [comment]
Ugh! I noticed that you've been adding lots of new features lately.  Surely it would be better to first concentrate on making the information that's presented more reliable?

**Comment by JTuwiner** [comment]
i didn't know the number there was so crucial...anyway, making it so this is calculated automatically now rather than manually. give me a fewmin

**Comment by JTuwiner** [comment]
ok it's automatic now

**Comment by superclarkk** [comment]
Brilliant! Thank you!

**Comment by JTuwiner** [comment]
no problem. let me know if you have any other requests and we'll do our best to add them
