### ISSUE TITLE
Wisconsin investment board puts $187 million into bitcoin

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#63]
One to add:

[Wisconsin investment board puts $187 million into bitcoin, cryptocurrency funds](https://eu.jsonline.com/story/money/business/2024/05/29/state-investment-board-puts-187-million-in-cryptocurrency-funds/73878457007/)

[More States to Follow Wisconsin in Buying Bitcoin ETFs, Says Finance Professor](https://cryptonews.com/news/wisconsin-bitcoin-etfs-finance-professor.htm)

**Comment by JTuwiner** [comment]
not including ETFs, besides the ETFs themselves

**Comment by superclarkk** [comment]
Yeah, I think you're right - this is already included in your data, via the ETF category. Please close.
