### ISSUE TITLE
Germany Bitcoin Sales

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#64]
It's been widely reported that Germany has been selling during the last few days.

See [news](https://www.google.com/search?q=germany+bitcoin&tbm=nws)

**Comment by superclarkk** [comment]
[https://platform.arkhamintelligence.com/explorer/entity/germany](https://platform.arkhamintelligence.com/explorer/entity/germany)

**Comment by superclarkk** [comment]
Any update on this? The Germany total value hasn't changed on the main page since I opened this ticket, despite it being widely known that the Gov has been selling.

The following has just been posted to a channel I follow. Details available on Arkham.

![image](https://github.com/BuyBitcoinWorldwide/bitcointreasuries/assets/8736514/fea98789-07de-4017-a256-efee7701b113)

**Comment by JTuwiner** [comment]
fixed
