### ISSUE TITLE
CleanSpark Inc not included in totals

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#65]
For the data published on August 4, 2024, the totals for the itemized **Mining** and itemized **Public Companies** sections have a discrepancy of 7,082, compared with their manually-calculated totals. This matches the CleanSpark Inc total.

This also affects the grand total at the top, by the same amount. The manually-calculated total is 2,682,606.76, whereas the published total is 2,622,496, which is a difference of 60,110.76. This should be approximately ~53,030.

**Comment by JTuwiner** [comment]
fixed
