### ISSUE TITLE
Telegram channel image does not match website, and website total has been reduced by 40,599 BTC in one day

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#69]
The latest total published in the [telegram channel](https://t.me/BTCTreasuries) does not match the website, and the website total has been reduced by 40,599 BTC in one day (from 2,549,892 on 23-10-2024 to 2,509,293 on 27-10-2024), despite the day's changes shown in telegram showing a net-addition of 8,109 BTC.

**Comment by superclarkk** [comment]
Screenshots showing the difference
![image](https://github.com/user-attachments/assets/a13c77e3-7d98-40b5-9db8-9042728ea001)
![Screenshot from 2024-10-28 09-56-15](https://github.com/user-attachments/assets/68ebdd35-340d-4f4e-a769-58cf7714d8de)

**Comment by JTuwiner** [comment]
mistake posting pic of etfs only
