### ISSUE TITLE
Neptune Digital now 105 BTC

### ISSUE THREAD

**Issue by slashiiii** [BuyBitcoinWorldwide/bitcointreasuries#7]
Hi, Neptune now has 105 BTC. They also operating miner now. Should increase arround 3 BTC per month.

https://neptunedigitalassets.com/neptune-expands-bitcoin-mining-operations-with-secured-order-of-next-gen-mining-machines/

**Comment by JTuwiner** [comment]
we're looking into this

**Comment by JTuwiner** [comment]
updated, thanks!
