### ISSUE TITLE
Did ARK really just reduce their holdings from 48,360.8 to 49.6?

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#71]
![Screenshot from 2024-11-12 18-23-29](https://github.com/user-attachments/assets/178f5f7f-9da0-4f21-bfd2-64664f13d6b4)

**Comment by superclarkk** [comment]
Bitcoin holdings available here:

https://assets.ark-funds.com/fund-documents/funds-etf-csv/ARK_21SHARES_BITCOIN_ETF_ARKB_HOLDINGS.csv

**Comment by JTuwiner** [comment]
fixing
