### ISSUE TITLE
Net outflow yesterday

### ISSUE THREAD

**Issue by superclarkk** [BuyBitcoinWorldwide/bitcointreasuries#72]
According to other sources, there was a net outflow yesterday (14 Nov), and yet [treasuries.bitbo.io](https://treasuries.bitbo.io/) recorded it as an inflow.

See [heyapollo.com](https://heyapollo.com/bitcoin-tracker/flows) and [farside.co.uk](https://farside.co.uk/btc/).

Can I ask, are you still updating the site manually? If so, that must be a nightmare. Is there any plan to crawl for the data?

**Comment by superclarkk** [comment]
![Screenshot from 2024-11-15 13-53-57](https://github.com/user-attachments/assets/3c4af270-4e98-4711-9299-266676c8bc36)

![image](https://github.com/user-attachments/assets/79df97ed-fa1e-4adc-b3f3-a2a63f5e809c)

**Comment by JTuwiner** [comment]
where are you seeing a net outflow on our site?

**Comment by superclarkk** [comment]
Sorry, I didn't see your message until now.  There was an outflow of 3,010 BTC on your site. May as well close this, and I'll let you know if it happens again.

Again, are you intending to crawl for the data and automatically update the site? Do you have a timescale? It would be nice to see this site competitive with the others, as I do prefer it in other ways.

**Comment by JTuwiner** [comment]
please tell me the page of the outflow

**Comment by JTuwiner** [comment]
one of my friends runs another site tracking this. our data is much better than theirs. trust me, crawling would lead to more complications than manually updating.

**Comment by superclarkk** [comment]
The screenshots above are from [heyapollo.com](https://heyapollo.com/bitcoin-tracker/flows) and [farside.co.uk](https://farside.co.uk/btc/).

Here are some others, although I haven't checked their accuracy:


https://sosovalue.com/assets/etf/us-btc-spot

https://charts.checkonchain.com/btconchain/etfs/etf_balance_0/etf_balance_0_light.html

https://www.theblock.co/data/crypto-markets/bitcoin-etf

https://dune.com/hildobby/btc-etfs

https://www.bitcoinstrategyplatform.com/etfs

https://cryptonary.com/bitcoin-etf-inflows-tracker/

https://coinank.com/etf/BtcEtfTable

https://www.bitcoinstrategyplatform.com/etfs

https://btcetffundflow.com/us

https://newhedge.io/terminal/bitcoin/bitcoin-etf-tracker
